### ISSUE TITLE
I Cannot Run Application

### ISSUE THREAD

**Issue by mitul06** [jinpark0625/react_shop#1]
Please provide me full steps of installing the application on the local machine.

I have node js 20 LTS version and didn't install the application, when I installed node module packages the given error node version mismatch. After that, when the node modules use **npm I --lagecy-peer-deps**, the run application  **npm starts**  but gives me an error as below.

```
 .eslintrc.js » eslint-config-standard-with-typescript:
        Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid:
        Value {"skipCompoundAssignments": false} should NOT have additional properties.
ERROR in [eslint] .eslintrc.js » eslint-config-standard-with-typescript:
        Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid:
        Value {"skipCompoundAssignments": false} should NOT have additional properties.
```

or  In Chrome inspect the console error show 

```
provider.ts:239 Uncaught Error: Component auth has not been registered yet
    at Provider. initialize (provider.ts:239:1)
    at initializeAuth (initialize.ts:66:1)
    at getAuth (index.ts:80:1)
    at ./src/api/firebase.ts (firebase.ts:63:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ./src/context/AuthContext.tsx (ProductTitle.tsx:18:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
initialize @ provider.ts:239
initializeAuth @ initialize.ts:66
getAuth @ index.ts:80
./src/api/firebase.ts @ firebase.ts:63
options. factory @ react refresh:6
__webpack_require__ @ bootstrap:22
fn @ hot module replacement:61
./src/context/AuthContext.tsx @ ProductTitle.tsx:18
options. factory @ react refresh:6
__webpack_require__ @ bootstrap:22
fn @ hot module replacement:61
./src/components/layout/Navbar.tsx @ MenuMobile.tsx:21
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:22
fn @ hot module replacement:61
./src/App.tsx @ bundle.js:21
options. factory @ react refresh:6
__webpack_require__ @ bootstrap:22
fn @ hot module replacement:61
./src/index.tsx @ useUser.tsx:69
options. factory @ react refresh:6
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
```

So please guide me on how to run the application with the proper steps.

**Comment by kumarbets** [comment]
Can you please help resolve this issue ? Looks like firebase/database has issue and showing service database is not avaiable.  This beautiful codebase can be used for firebase related tasks

**Comment by jinpark0625** [comment]
> Can you please help resolve this issue ? Looks like firebase/database has issue and showing service database is not avaiable.  This beautiful codebase can be used for firebase related tasks

Oops! I'm sorry. I just noticed the issue now. I will check the problem and leave a comment again.

**Comment by kumarbets** [comment]
By removing ^ from firebase 9.16.0 it is working good. Just firebase crap..haha otherwise ur design looks very cool except that lot of types combined and may cause confusion for starters. Otherwise looks good and react query + react hook form is awsome combo that makes the ap smooth. Keep react for visibility and handle user interaction thru react hook form, handle server state thru tanstack - makes web app super smooth

**Comment by kumarbets** [comment]
also added new product to firestore, as getproducts is on firestore.
